### PR TITLE
fix-#333: add extra info on UI

### LINKED ISSUE #333: Add links for each implementation details modal
So, implementation details can also include "additional" links, which is basically a map of url -> description. Looks like all the data is accessible in code, but it just needs to be displayed. Maybe even more data could be displayed like: homepage, issues url - there probably would be some redundancy, but why not?
image

### PR DESCRIPTION
**Pull request by Siddharth-Singh-2004**
fix #333: Added code to Implementation Info page to display Additional Links (URLs) provided by JSON schema implementers.

----
📚 Documentation preview 📚: https://bowtie-json-schema--879.org.readthedocs.build/en/879/

### CODE REVIEW

File: frontend/src/components/ImplementationReportView/ImplementationReportView.tsx [hunk 1]
```diff
@@ -121,6 +121,22 @@ const ReportComponent: React.FC<{ implementation: Implementation }> = ({
                   </ul>
                 </td>
               </tr>
+              {implementation.links && !!implementation.links.length && (
```
Comment (harrel56) [inline frontend/src/components/ImplementationReportView/ImplementationReportView.tsx:124]: I think this potentially can be shortened to `implementation.links?.length`

**Review by harrel56 — APPROVED** [review]
lgtm!

File: frontend/src/components/ImplementationReportView/ImplementationReportView.tsx (hunk 1 above)
Comment (Siddharth-Singh-2004) [reply frontend/src/components/ImplementationReportView/ImplementationReportView.tsx:124]: I agree.

Comment (Siddharth-Singh-2004) [reply frontend/src/components/ImplementationReportView/ImplementationReportView.tsx]: @harrel56, kindly review.

**Review by harrel56 — APPROVED** [review]

**Comment by Julian** [comment]
Feel free to merge in general of course :)

**Comment by Julian** [comment]
Thanks @Siddharth-Singh-2004 !

**Comment by Siddharth-Singh-2004** [comment]
@harrel56,

Sorry for the back and forth. The shortened code seems to be causing issue with the UI. 

Picking a schema that has not provided additional links, for example, jsonschema Go (1st one on the list).

The shortened code, implementation.links?.length, leads to a UI bug (see the 0 displayed):
screen1

The long form of code, implementation.links && !!implementation.links.length, meets to expected behavior:
screen2

The shortened version seems to be printing the value of length when there is no link to display. I'll revert to the long form of code.
